# Libraries & Dataframes

In [1]:
import pandas as pd

In [2]:
df_cluster_OT = pd.read_csv("../resources/df_cluster_OT.csv")
df_cluster_LDA = pd.read_csv("../resources/df_cluster_LDA.csv")
df_sentiment_analysis = pd.read_csv("../resources/df_sentiment.csv")

In [3]:
df_sentiment_analysis.head()

,Review,Liked,polarity,sentiment_type,sentiment_binary
0,Wow... Loved this place.,1,0.40,Positive,1
1,Crust is not good.,0,-0.35,Negative,0
2,Not tasty and the texture was just nasty.,0,-1.00,Negative,0
3,Stopped by during the late May bank holiday of...,1,0.20,Positive,1
4,The selection on the menu was great and so wer...,1,0.80,Positive,1

In [4]:
df_cluster_OT.head()

   cluster_OT
0           7
1           0
2           3
3           6
4           1

In [5]:
df_cluster_LDA.head()

,dominant_topic_LDA,topic_percentage_contribution,keywords,Review,Liked
0,7.0,0.1154,"love, amazing, taste, meal, bland, find, suck,...",Wow... Loved this place.,1
1,4.0,0.1175,"good, quality, thing, enjoy, sushi, price, dis...",Crust is not good.,0
2,4.0,0.1132,"good, quality, thing, enjoy, sushi, price, dis...",Not tasty and the texture was just nasty.,0
3,9.0,0.1169,"friendly, minute, chicken, pizza, menu, price,...",Stopped by during the late May bank holiday of...,1
4,9.0,0.1235,"friendly, minute, chicken, pizza, menu, price,...",The selection on the menu was great and so wer...,1

In [6]:
REVIEW = "Review"
LIKED = "Liked"

POLARITY = "polarity"
SENTIMENT_TYPE = "sentiment_type"
SENTIMENT_BINARY = "sentiment_binary"

CLUSTER_OT = "cluster_OT"

DOMINANT_TOPIC_LDA = "dominant_topic_LDA"
TOPIC_PERCENTAGE_CONTRIBUTION = "topic_percentage_contribution"
KEYWORDS = "keywords"

# Results comparison

### Merge all needed variables generated from previous notebooks

In [14]:
def merge_column_results(df_LDA: pd.DataFrame, df_OT: pd.DataFrame, df_SA: pd.DataFrame) -> pd.DataFrame:
    final_df = pd.merge(df_LDA, df_OT, left_index=True, right_index=True)
    final_df = pd.merge(final_df, df_SA, left_index=True, right_index=True)
    final_df = final_df[["Review_x", "Liked_x", POLARITY, SENTIMENT_BINARY, SENTIMENT_TYPE, 
                         CLUSTER_OT, DOMINANT_TOPIC_LDA, TOPIC_PERCENTAGE_CONTRIBUTION, KEYWORDS]]
    final_df.columns = [REVIEW, LIKED, POLARITY, SENTIMENT_BINARY, SENTIMENT_TYPE, 
                        CLUSTER_OT, DOMINANT_TOPIC_LDA, TOPIC_PERCENTAGE_CONTRIBUTION, KEYWORDS]
    return final_df

In [15]:
df_comparison = merge_column_results(df_cluster_LDA, df_cluster_OT, df_sentiment_analysis)
df_comparison.head()

,Review,Liked,polarity,sentiment_binary,sentiment_type,cluster_OT,dominant_topic_LDA,topic_percentage_contribution,keywords
0,Wow... Loved this place.,1,0.40,1,Positive,7,7.0,0.1154,"love, amazing, taste, meal, bland, find, suck,..."
1,Crust is not good.,0,-0.35,0,Negative,0,4.0,0.1175,"good, quality, thing, enjoy, sushi, price, dis..."
2,Not tasty and the texture was just nasty.,0,-1.00,0,Negative,3,4.0,0.1132,"good, quality, thing, enjoy, sushi, price, dis..."
3,Stopped by during the late May bank holiday of...,1,0.20,1,Positive,6,9.0,0.1169,"friendly, minute, chicken, pizza, menu, price,..."
4,The selection on the menu was great and so wer...,1,0.80,1,Positive,1,9.0,0.1235,"friendly, minute, chicken, pizza, menu, price,..."

### Compare sentiment_type between optimal transport and LDA methods

In [20]:
def display_clutsers_sentiment(df: pd.DataFrame, cluster_var: str) -> dict:
    df_count = pd.crosstab(df[cluster_var], df[SENTIMENT_TYPE], margins=True, margins_name="Total")
    df_percent = pd.crosstab(df[cluster_var], df[SENTIMENT_TYPE], normalize="index")
    return {"DF_COUNT": df_count,"DF_PERCENT": df_percent}

In [22]:
display_clutsers_sentiment(df_comparison, CLUSTER_OT)["DF_PERCENT"]

sentiment_type  Negative  Positive
cluster_OT
0               0.574074  0.425926
1               0.455882  0.544118
2               0.534091  0.465909
3               0.535714  0.464286
4               0.482759  0.517241
5               0.385542  0.614458
6               0.500000  0.500000
7               0.493333  0.506667
8               0.484375  0.515625
9               0.446154  0.553846

In [23]:
display_clutsers_sentiment(df_comparison, DOMINANT_TOPIC_LDA)["DF_PERCENT"]

sentiment_type      Negative  Positive
dominant_topic_LDA
0.0                 0.593103  0.406897
1.0                 0.583893  0.416107
2.0                 0.429825  0.570175
3.0                 0.545455  0.454545
4.0                 0.428571  0.571429
5.0                 0.389610  0.610390
6.0                 0.311688  0.688312
7.0                 0.372549  0.627451
8.0                 0.540230  0.459770
9.0                 0.520548  0.479452